# Нейронные сети

## Домашнее задание 2: numpy и функции

# Light

### Задача 1

Подгрузите файл **train_vector_1.csv** с помощью функции **np.loadtxt**. Назовите подгруженный массив my_array. Убедитесь, что подгруженный массив имеет тип np.ndarray

https://drive.google.com/open?id=1ngnrhmoMInequrA6JyAe90lEPhcbi0iH

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [5]:
# грузим массив из файла .csv
import numpy as np
my_array = np.loadtxt('/content/drive/My Drive/train_vector_1.csv', delimiter=',')
type(my_array)

numpy.ndarray

In [6]:
my_array

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ])

### Задача 2

Напишите код, который считает среднее значение всех элементов массива (без использования встроенных функций np.mean и т.д.)
* Примените ее к подгруженному массиву my_array
* Преобразуйте массив my_array в список, сохраните его в переменной my_list
* Примените функцию к списку my_list
* Сравните производительность по времени написанного вами кода в зависимости от типа данных (список и np.array), для этого используйте %%timeit

In [11]:
def my_mean(m):
  count = 0
  summa = 0
  for i in m:
    count += 1
    summa += i
  return summa/count

print(my_mean(my_array))
# this is test
assert my_mean([i for i in range(1, 11)]) == 5.5

3.057333333333334


In [26]:
my_list = my_array.tolist()
type(my_list)

list

In [27]:
print(type(my_array))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [28]:
%%timeit
my_mean(my_array)


The slowest run took 5.70 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 34.4 µs per loop


In [29]:
%%timeit
my_mean(my_list)

100000 loops, best of 3: 6.87 µs per loop


In [21]:
%%timeit
my_array.mean()

The slowest run took 20.18 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.55 µs per loop


In [25]:
print(len(my_list))
print(len(my_array))
print(my_array.shape)

150
150
(150,)


In [33]:
def my_mean1(m):
  summa = 0
  for i in range(len(m)):
    summa += m[i]
  return summa/len(m)

print(my_mean(my_array))
# this is test
assert my_mean([i for i in range(1, 11)]) == 5.5

3.057333333333334


In [34]:
%%timeit
my_mean1(my_list)

100000 loops, best of 3: 6.29 µs per loop


In [35]:
%%timeit
my_mean1(my_array)

10000 loops, best of 3: 36.1 µs per loop


We were so surprised that regular lists work faster that they spammed three tons of water in common chat))

### Задача 3

Подгрузите файл **iris.csv** с помощью встроенной функции **np.loadtxt**. Назовите его my_2d_array. Напиишите код, который считает сумму элементов массива по столбцам. 

In [40]:
# грузим массив из файла .csv
my_2d_array = np.loadtxt('/content/drive/My Drive/iris.csv', delimiter=',', skiprows=1) # skiprows=1 - пропускаем первую строку, поскольку в ней названия колонок базы
print(my_2d_array.shape)
my_2d_array.sum(axis = 0)

(150, 5)


array([11175. ,   876.5,   458.6,   563.7,   179.9])

### Задача 4 

* Используя библиотеку numpy, создайте массив 3x3, значения которого находятся в диапазоне от 11 до 40. 

* Не используя цикл for,  выведите на экран список элементов, которые меньше 20.

* Просуммируйте все элементы (не используя цикл for)


In [45]:
from random import randint

m = np.zeros((3,3))
for i in range(0,3):
  for j in range(0,3):
    m[i][j] = randint(11, 40)
m

array([[27., 25., 29.],
       [16., 14., 11.],
       [16., 35., 27.]])

In [50]:
mask = m < 20
print(mask)
print(m[mask])

[[False False False]
 [ True  True  True]
 [ True False False]]
[16. 14. 11. 16.]


In [53]:
a = np.sum(m)
print(a)

200.0


### Задача 5

* Создайте массив, который будет содержать списки с именем студента(str), его возрастом(int) и средней оценкой(float). 
* Отсортируйте такой массив
* Замените значение, отвечающее за возраст, у всех студентов на одно и то же, например, 10. Отсортируйте такой массив теперь. 

In [56]:
t5 = np.array([['Вася', 50, 3.76], ['Петя', 70, 4.32], ['Оля', 20, 4.92]])
t5.sort()
t5

array([['3.76', '50', 'Вася'],
       ['4.32', '70', 'Петя'],
       ['20', '4.92', 'Оля']], dtype='<U4')

In [58]:
t5_1 = np.array([['Вася', 10, 3.76], ['Петя', 10, 4.32], ['Оля', 10, 4.92]])
t5_1.sort()
t5_1

array([['10', '3.76', 'Вася'],
       ['10', '4.32', 'Петя'],
       ['10', '4.92', 'Оля']], dtype='<U4')

In [0]:
# mm, okey, it happened because np.array transform every element in str, because he can use only one type elements and '1' always first

## Pro версия

### Задача 1

* Подгрузите массив **iris.csv** и назовите его my_array. 

* В документации библиотеки numpy найдите функцию, генерирующую случаные числа.

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array.

* Назовите его my_generated_array

In [0]:
my_array = np.loadtxt('/content/drive/My Drive/iris.csv', delimiter=',', skiprows=1)
rng = np.random.default_rng()
my_generated_array = rng.random((my_array.shape))
my_generated_array

### Задача 2

* Выполните поэлементное умножение my_array на my_generated_array

* Склейте массивы my_array, my_generated_array в один

* Возьмите склеенный массив и разделите его на равные части (больше двух)

In [0]:
print(my_array * my_generated_array)

In [66]:
print(np.concatenate((my_array, my_generated_array), axis = 0))

[[0.00000000e+00 5.10000000e+00 3.50000000e+00 1.40000000e+00
  2.00000000e-01]
 [1.00000000e+00 4.90000000e+00 3.00000000e+00 1.40000000e+00
  2.00000000e-01]
 [2.00000000e+00 4.70000000e+00 3.20000000e+00 1.30000000e+00
  2.00000000e-01]
 ...
 [6.12787326e-01 4.03568733e-01 4.95746874e-01 4.73018948e-01
  3.55305703e-01]
 [3.12547240e-01 9.80880545e-01 4.43716695e-01 6.49267449e-01
  9.07304780e-04]
 [3.34554929e-01 8.02726309e-01 3.14084629e-02 7.98496334e-01
  7.54246112e-01]]


In [0]:
last_array = np.concatenate((my_array, my_generated_array), axis = 0)
last_array.reshape(4, int(last_array.shape[0]/4), last_array.shape[1])
# or more right
np.split(last_array, 3)

### Задача 3

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием

In [76]:
my_array[(my_array > 3) & (my_array < 5)]

array([3.5, 4.9, 4.7, 3.2, 4.6, 3.1, 4. , 3.6, 3.9, 4.6, 3.4, 3.4, 4.4,
       4.9, 3.1, 3.7, 4.8, 3.4, 4.8, 4.3, 4. , 4.4, 3.9, 3.5, 3.8, 3.8,
       3.4, 3.7, 4.6, 3.6, 3.3, 4.8, 3.4, 3.4, 3.5, 3.4, 4.7, 3.2, 4.8,
       3.1, 3.4, 4.1, 4.2, 4.9, 3.1, 3.2, 3.5, 4.9, 3.6, 4.4, 3.4, 3.5,
       4.5, 4.4, 3.2, 3.5, 3.8, 4.8, 3.8, 4.6, 3.2, 3.7, 3.3, 3.2, 4.7,
       3.2, 4.5, 3.1, 4.9, 4. , 4.6, 4.5, 3.3, 4.7, 4.9, 3.3, 4.6, 3.9,
       3.5, 4.2, 4. , 4.7, 3.6, 3.1, 4.4, 4.5, 4.1, 4.5, 3.9, 3.2, 4.8,
       4. , 4.9, 4.7, 4.3, 4.4, 4.8, 4.5, 3.5, 3.8, 3.7, 3.9, 4.5, 3.4,
       4.5, 3.1, 4.7, 4.4, 4.1, 4. , 4.4, 4.6, 4. , 3.3, 4.2, 4.2, 4.2,
       4.3, 4.1, 3.3, 4.9, 4.5, 3.6, 3.2, 3.2, 3.8, 3.2, 4.9, 4.9, 3.3,
       3.2, 4.8, 4.9, 3.8, 3.4, 3.1, 4.8, 3.1, 3.1, 3.1, 3.2, 3.3, 3.4])

### Задача 4

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных вещественных чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random...

In [28]:
rr = np.random.randint(15, 38, (2,3,4))
print(rr)

[[[35 35 16 33]
  [30 23 16 31]
  [35 37 33 28]]

 [[15 17 31 29]
  [26 32 25 27]
  [25 25 25 35]]]


### Задача 5

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

In [49]:
rr = np.where(rr<20,'small', np.where(rr>30,'large', 'medium'))
rr

array([[['large', 'large', 'small', 'large'],
        ['medium', 'medium', 'small', 'large'],
        ['large', 'large', 'large', 'medium']],

       [['small', 'small', 'large', 'medium'],
        ['medium', 'large', 'medium', 'medium'],
        ['medium', 'medium', 'medium', 'large']]], dtype='<U6')

### Задача 6

Создайте одномерный массив из случайных 10 значений. 

* Не используя цикл for, сумму значений с 3 по 7 элемент.
* Найдите сумму квадратов последних двух элементов.

In [6]:
randy = np.random.sample(10)
randy

array([0.58721121, 0.61904111, 0.30478246, 0.43512747, 0.10977834,
       0.61835879, 0.23953021, 0.22077853, 0.24121676, 0.19441362])

In [13]:
print(randy[2:7].sum())
sum([0.30478246, 0.43512747, 0.10977834, 0.61835879, 0.23953021])

1.707577277892164


1.70757727

In [0]:
assert round(sum([0.30478246, 0.43512747, 0.10977834, 0.61835879, 0.23953021]),2) == round(randy[2:7].sum(), 2)

In [20]:
print(randy[-2:]**2)
# this is test
[randy[-2]**2, randy[-1]**2]

[0.05818552 0.03779665]


[0.058185523303008635, 0.03779665391757645]